# Generated by Django 4.1.7 on 2023-03-29 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=5)),
                ('conn', models.BooleanField(default=False)),
                ('device_name', models.CharField(blank=True, max_length=50, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'device_connection_rt',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('device_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveattendance.deviceconnection')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
