# Generated by Django 4.1.7 on 2023-03-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveattendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosActivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('tarifa', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
                ('fechainicio', models.DateField()),
                ('fechavencimiento', models.DateField()),
                ('diasrestantes', models.IntegerField()),
            ],
            options={
                'db_table': 'usuariosactivos_at',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='deviceconnection',
            table='device_connection_at',
        ),
    ]
