# Generated by Django 4.1.7 on 2023-03-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=5)),
                ('conn', models.BooleanField(default=True)),
            ],
        ),
    ]
