# Generated by Django 4.1.7 on 2023-03-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicezk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconnection',
            name='zk',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deviceconnection',
            name='conn',
            field=models.BooleanField(null=True),
        ),
    ]
