# Generated by Django 4.1.7 on 2023-03-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicezk', '0003_remove_deviceconnection_zk_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deviceconnection',
            table='device_connection',
        ),
    ]
