# Generated by Django 4.1.7 on 2023-03-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicezk', '0004_alter_deviceconnection_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconnection',
            name='conn',
            field=models.BooleanField(default=False),
        ),
    ]
