# Generated by Django 4.1.7 on 2023-03-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicezk', '0005_alter_deviceconnection_conn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconnection',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deviceconnection',
            name='serial_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
