# Generated by Django 4.1.7 on 2023-03-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosActivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
                ('fechainicio', models.DateField()),
                ('fechavencimiento', models.DateField()),
            ],
            options={
                'db_table': 'usuarios_activos',
                'managed': False,
            },
        ),
    ]
